name: Run Tests
on:
  pull_request:
      branches:
        - main

jobs:
  build-deploy:
    name: Run Tests
    runs-on: ubuntu-22.04 # latest version 24 has incompatibility issues (playwright)
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with:
          node-version: 18

      - name: Install gcds-components
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build repo
        run: npm run build

      - name: Run tests
        run: npm run test
